version: "3.7"

services:
  web:
    build: ./web

    volumes:
      - ./web:/usr/src/app

    expose:
      - "8000"

    networks:
      - app_network

    env_file:
      - .env-prod

    restart: always

    command: ./run_django.sh

  nginx:
    build:
      context: ./nginx
      args:
        ENV: prod

    depends_on:
      - web

    ports:
      - "80:80"

    env_file:
      - .env-prod

    networks:
      - app_network

    restart: always

  postgres:
    build: ./postgres

    env_file:
      - .env-prod

    expose:
      - "5432"

    volumes:
      - app-pgdata:/var/lib/postgresql/data

    networks:
      - app_network

    restart: always

networks:
  app_network:

volumes:
  app-pgdata:
