# Generated by Django 4.0.3 on 2022-03-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_helpgiver_province_helpgiver_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofhelp',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
