name: Deployment

concurrency: production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) nginx Docker
        id: meta_nginx
        uses: docker/metadata-action@v2
        with:
          images: valeriodocker/refugeeshelper_nginx

      - name: Build and push nginx Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          build-args: ENV=prod
          push: true
          tags: ${{ steps.meta_nginx.outputs.tags }}
          labels: ${{ steps.meta_nginx.outputs.labels }}

      - name: Extract metadata (tags, labels) for web Docker
        id: meta_web
        uses: docker/metadata-action@v2
        with:
          images: valeriodocker/refugeeshelper_web

      - name: Build and push web Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
      
      - name: Extract metadata (tags, labels) for postgresql Docker
        id: meta_postgresql
        uses: docker/metadata-action@v2
        with:
          images: valeriodocker/refugeeshelper_postgresql

      - name: Build and push postgresql Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./postgres
          push: true
          tags: ${{ steps.meta_postgresql.outputs.tags }}
          labels: ${{ steps.meta_postgresql.outputs.labels }}