name: Deployment

concurrency: production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Env variable
env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta_nginx
        uses: docker/metadata-action@v2
        with:
          images: valeriodocker/refugeeshelper_nginx

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          build-args:
            ENV: production
          push: true
          tags: ${{ steps.meta_nginx.outputs.tags }}
          labels: ${{ steps.meta_nginx.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta_web
        uses: docker/metadata-action@v2
        with:
          images: valeriodocker/refugeeshelper_web

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}